export default (Fonts = {
  Regular: "Montserrat-Regular",
  ExtraBold: "Montserrat-ExtraBold",
  BoldItalic: "Montserrat-BoldItalic",
  Black: "Montserrat-Black",
  Medium: "Montserrat-Medium",
  Bold: "Montserrat-Bold",
  Light: "Montserrat-Light",
  SemiBold: "Montserrat-SemiBold",
  LightItalic: "Montserrat-LightItalic",
  ExtraLight: "Montserrat-ExtraLight",
  ExtraLightItalic: "Montserrat-ExtraLightItalic",
  SemiBoldItalic: "Montserrat-SemiBoldItalic",
  ThinItalic: "Montserrat-ThinItalic",
  Thin: "Montserrat-Thin",
  BlackItalic: "Montserrat-BlackItalic",
  Italic: "Montserrat-Italic",
  MediumItalic: "Montserrat-MediumItalic",
  ExtraBoldItalic: "Montserrat-ExtraBoldItalic",
  Hyperspace: "Hyperspace",
  HyperspaceBold: "Hyperspace-Bold",
  HyperspaceItalic: "Hyperspace-Italic",
  HyperspaceBoldItalic: "Hyperspace-BoldItalic",
});
