
platform :ios, '9.0'

target 'DroidconBoston' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
